version: '3'
services:
  web:
    build: .
    ports:
     - "5000:80"
    environment:
      - Osero_WEB_Client_User= #User name of Osero server
      - Osero_WEB_Client_PASS= #User password of Osero server
    volumes:
      - .:/usr/src/app